---
all:
  children:
    vds:
      hosts:
        zelgray.cherkasy.ua:
          ansible_host: "ssh.zelgray.cherkasy.ua"
          ansible_user: "zelgray"
          ansible_python_interpreter: "/usr/bin/python3"
...
